apiVersion: apps/v1
kind: Deployment
metadata:
  name: irctc-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: irctc-frontend
  template:
    metadata:
      labels:
        app: irctc-frontend
    spec:
      containers:
        - name: frontend
          image: irctc-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: irctc-frontend
spec:
  selector:
    app: irctc-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
